---
- name: Install default packages
  hosts: all
  become: true
  tasks:
  - name: Install default packages
    apt:
      upgrade=dist
      update_cache=yes
      state: latest
      name:
        - python3
        - python3-pip
        - build-essential
        - git
        - virtualenvwrapper
        - rsync
        - tmux
