HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt extendedglob notify
unsetopt nomatch
bindkey -e

zstyle :compinstall filename '$HOME/.zshrc'

autoload -Uz compinit
compinit

##############################################################
##################### Antigen Config #########################
if [[ ! -f $HOME/antigen.zsh ]]; then
   curl -L git.io/antigen > $HOME/antigen.zsh
fi

source $HOME/antigen.zsh

#ANTIGEN_LOG=$HOME/.antigen.log

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).

antigen bundle git
antigen bundle archlinux
antigen bundle pip
antigen bundle command-not-found
antigen bundle cp
antigen bundle colored-man-pages

antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting

antigen bundle unixorn/autoupdate-antigen.zshplugin

# Load the theme.
antigen theme bureau
#antigen theme af-magic

# Tell Antigen that you're done.
antigen apply

##############################################################

#Add Aliases
alias j="sudo journalctl -xb"
alias mountnfs="sudo mount nfs.gtel.ufc.br:/home/users /home/jpinheiro/nfs-gtel"

#Virtualenv
if [[ -f /usr/bin/virtualenvwrapper.sh ]]; then
    export WORKON_HOME=~/.virtualenvs
    source /usr/bin/virtualenvwrapper.sh
fi

# Tilix
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
        source /etc/profile.d/vte.sh
fi
