HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt extendedglob notify
unsetopt nomatch
bindkey -e

zstyle :compinstall filename '$HOME/.zshrc'

autoload -Uz compinit
compinit

##############################################################
##################### Antigen Config #########################
if [[ ! -f $HOME/antigen.zsh ]]; then
   curl -L git.io/antigen > $HOME/antigen.zsh
fi

source $HOME/antigen.zsh

#ANTIGEN_LOG=$HOME/.antigen.log

#ZSH_TMUX_AUTOSTART=true

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).

#antigen bundle git
#antigen bundle cp
#antigen bundle archlinux
antigen bundle tmux
antigen bundle pip
antigen bundle command-not-found
antigen bundle colored-man-pages

antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting

antigen bundle unixorn/autoupdate-antigen.zshplugin

# Load the theme.
antigen theme bureau
#antigen theme af-magic

# Tell Antigen that you're done.
antigen apply

##############################################################

#Add Aliases
source ~/git-repos/myscripts/configs/aliases

#Virtualenv
if [[ -f /usr/bin/virtualenvwrapper.sh ]]; then
    export WORKON_HOME=~/.virtualenvs
    source /usr/bin/virtualenvwrapper.sh
fi

# Tilix
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
    source /etc/profile.d/vte.sh
fi

if [ ! -f ~/.emacs.d/spacemacs.mk ]; then
    git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
fi

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/jpinheiro/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/jpinheiro/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/jpinheiro/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/jpinheiro/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

