HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt extendedglob notify
unsetopt nomatch
bindkey -e

zstyle :compinstall filename '$HOME/.zshrc'

autoload -Uz compinit
compinit

##############################################################
##################### Antigen Config #########################
if [[ ! -f $HOME/antigen.zsh ]]; then
   curl -L git.io/antigen > $HOME/antigen.zsh
fi

source $HOME/antigen.zsh

#ANTIGEN_LOG=$HOME/.antigen.log

#ZSH_TMUX_AUTOSTART=true

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).

#antigen bundle git
#antigen bundle cp
#antigen bundle archlinux
antigen bundle tmux
antigen bundle pip
antigen bundle command-not-found
antigen bundle colored-man-pages

antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting

antigen bundle unixorn/autoupdate-antigen.zshplugin

# Load the theme.
antigen theme bureau
#antigen theme af-magic

# Tell Antigen that you're done.
antigen apply

##############################################################

#Add Aliases
source ~/git-repos/myscripts/configs/aliases

#Virtualenv
if [[ -f /usr/bin/virtualenvwrapper.sh ]]; then
    export WORKON_HOME=~/.virtualenvs
    source /usr/bin/virtualenvwrapper.sh
elif [[ -f /usr/share/virtualenvwrapper/virtualenvwrapper.sh ]]; then
    export WORKON_HOME=~/.virtualenvs
    source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
fi

# Tilix
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
    source /etc/profile.d/vte.sh
fi

if [ ! -f ~/.emacs.d/spacemacs.mk ]; then
    git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
fi

#if [ -z "$SSH_AUTH_SOCK" ] ; then
#    eval `ssh-agent -s` >> /dev/null
#    ssh-add -q
#fi
